server:
  host: ${PCS_SERVER_HOST:localhost}
  port: ${PCS_SERVER_PORT:8080}
  servlet:
    session:
      timeout: ${PCS_SERVLET_SESSION_TIMEOUT:5m}

spring:

  jpa:
    database-platform: org.hibernate.dialect.${PCS_HIBERNATE_DIALECT:H2Dialect}
    hibernate:
      ddl-auto: ${PCS_DDL_AUTO:update}

  datasource:
    driver-class-name: ${PCS_DB_DRIVER_CLASS:org.h2.Driver}
    url: ${PCS_DB_URL:jdbc:h2:file:./db/picasso_db;AUTOSERVER=true;MODE=MYSQL;DB_CLOSE_ON_EXIT=false}
    username: ${PCS_DB_USERNAME:picasso}
    password:

    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

logging:
  level: debug

