server:
  host: ${PCS_SERVER_HOST:localhost}
  port: ${PCS_SERVER_PORT:8080}
  servlet:
    session:
      timeout: ${PCS_SERVLET_SESSION_TIMEOUT:5m}
    context-path: /picasso

spring:
  profiles:
    active: ${PCS_SPRING_PROFILE}

  jpa:
    database-platform: org.hibernate.dialect.${PCS_HIBERNATE_DIALECT:MySQLDialect}
    hibernate:
      ddl-auto: ${PCS_DDL_AUTO:none}

  datasource:
    driver-class-name: ${PCS_DB_DRIVER_CLASS:com.mysql.cj.jdbc.Driver}
    url: ${PCS_DB_URL:jdbc:mysql://localhost:3306/picasso_db}
    username: ${PCS_DB_USERNAME:picasso}
    password: ${PCS_DB_PASSWORD}

    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

logging:
  level: info

