spring:
  profiles:
    active: ${PCS_SPRING_PROFILE}

  servlet:
    multipart:
      max-file-size: ${PCS_MAX_FILE_SIZE:10MB}
      max-request-size: ${spring.servlet.multipart.max-file-size}

  jpa:
    database-platform: org.hibernate.dialect.${PCS_HIBERNATE_DIALECT:MySQLDialect}
    hibernate:
      ddl-auto: ${PCS_DDL_AUTO:none}

  datasource:
    driver-class-name: ${PCS_DB_DRIVER_CLASS:com.mysql.cj.jdbc.Driver}
    url: ${PCS_DB_URL:jdbc:mysql://localhost:3306/picasso_db}
    username: ${PCS_DB_USERNAME:picasso}
    password: ${PCS_DB_PASSWORD}

    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

server:
  host: ${PCS_SERVER_HOST:localhost}
  port: ${PCS_SERVER_PORT:8080}
  servlet:
    session:
      timeout: ${PCS_SERVLET_SESSION_TIMEOUT:5m}
    context-path: /picasso

logging:
  level:
    org.novinomad.picasso: info
    org.hibernate.SQL: error

app:
  jobs:
    enabled: false

  tour-files-folder: ${PCS_TOUR_FILES_FOLDER:./toursFiles}

  date:
    format:
      ui-date-time: ${PCS_UI_DATE_TIME_FORMAT:dd MMM yyyy HH:mm}
      ui-date: ${PCS_UI_DATE_FORMAT:dd MMM yyyy}
      gantt-task: ${PCS_GANTT_TASK_DATE_TIME_FORMAT:dd mon yyyy HH:mi}
      gantt-major: ${PCS_GANTT_MAJOR_DATE_FORMAT:dd mon yyyy}
      date-range-picker: ${PCS_DATE_RANGE_PICKER_DATE_TIME_FORMAT:DD MMM YYYY HH:mm}



