server:
  host: ${PCS_SERVER_HOST:localhost}
  port: ${PCS_SERVER_PORT:8080}
  servlet:
    session:
      timeout: ${PCS_SERVLET_SESSION_TIMEOUT:5m}
    context-path: /picasso

spring:
  profiles:
    active: ${PCS_SPRING_PROFILE:dev}

  servlet:
    multipart:
      max-file-size: ${PCS_MAX_FILE_SIZE:10MB}
      max-request-size: ${spring.servlet.multipart.max-file-size}

  jpa:
    database-platform: org.hibernate.dialect.${PCS_HIBERNATE_DIALECT:MySQLDialect}
    hibernate:
      ddl-auto: ${PCS_DDL_AUTO:update}

    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  datasource:
    driver-class-name: ${PCS_DB_DRIVER_CLASS:com.mysql.cj.jdbc.Driver}
    url: ${PCS_DB_URL:jdbc:mysql://localhost:3306/picasso_db}
    username: ${PCS_DB_USERNAME:picasso}
    password: ${PCS_DB_PASSWORD}

    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  mail:
    host: ${SMPT_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.novinomad.picasso: debug
    org.hibernate.SQL: error

app:
  jobs:
    enabled: false

  tour-files-folder: ${PCS_TOUR_FILES_FOLDER:./toursFiles}
  default-table-page-size: 25
  date:
    format:
      ui-date-time: ${PCS_UI_DATE_TIME_FORMAT:dd MMM yyyy HH:mm}
      ui-date: ${PCS_UI_DATE_FORMAT:dd MMM yyyy}
      gantt-task: ${PCS_GANTT_TASK_DATE_TIME_FORMAT:dd mon yyyy HH:mi}
      gantt-major: ${PCS_GANTT_MAJOR_DATE_FORMAT:dd mon yyyy}
      date-range-picker: ${PCS_DATE_RANGE_PICKER_DATE_TIME_FORMAT:DD MMM YYYY HH:mm}

super-admin-password: ${SUPER_ADMIN_PASSWORD}



